# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-09-23 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mako_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('biz', models.CharField(max_length=30)),
                ('machine_numbers', models.IntegerField()),
                ('celery_id', models.CharField(max_length=30)),
                ('status', models.CharField(default='queue', max_length=30)),
                ('argument', models.CharField(blank=True, max_length=30, null=True)),
                ('log', models.TextField(blank=True, null=True)),
                ('result', models.BooleanField(default=False)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mako_application.Script')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
